### ISSUE TITLE
Hosting your slides

### ISSUE THREAD

**Issue by gabrielle-ong** [jaymierosen/lunch-learn#1]
Hi Jaymie! Wasn't able to make it to your talk but thank you for sharing your slides! And for sharing your perspective and advice on mental health in tech. 

Just a suggestion to make your slides more accessible to those who aren't github savy - perhaps host them online? An easy npm package I've used to host my slides is https://surge.sh/ Makes sharing your reveal.js slides easy as sending a link :) Hope you consider it!

**Comment by jaymierosen** [comment]
Hi Gabrielle! No problem, hope you find the info helpful! :)

Oh that's awesome! Thanks for the suggestion!!

**Comment by jaymierosen** [comment]
@gabrielle-ong - slides are located here: http://lunch-learn-mental-health.surge.sh/ -- enjoy, and thanks again for the awesome solution.
